const sentencesPool = {
    cs: [
        "Rychlá hnědá liška přeskakuje líného psa.",
        "Závodění není jen o rychlosti, ale také o soustředění a přesnosti.",
        "Abyste skončili první, musíte nejdříve dojet do cíle.",
        "Sledujte cestu a držte ruce pevně na klávesnici.",
        "Rychlé psaní je jako řazení rychlostních stupňů v závodním autě.",
        "Vítězství patří tomu, kdo udělá nejméně chyb.",
        "Motor řve, když zelené světlo signalizuje start posledního kola.",
        "Cvičení dělá mistra, pokud jde o dovednosti psaní všemi deseti.",
        "Pravidelný rytmus je důležitější než náhlý nárůst rychlosti.",
        "Dav jásá, když vedoucí jezdec protne cílovou čáru.",
        "Vozy formule jedna mohou na dlouhých rovinkách dosáhnout úžasných rychlostí.",
        "Soustřeďte se nejdříve na přesnost a rychlost přijde sama.",
        "Každý napsaný znak vás přibližuje k šachovnicové vlajce.",
        "Nedívejte se zpět, soupeř vám dýchá na záda.",
        "Pneumatiky skřípou, když auto projíždí ostrou zatáčku ve vysoké rychlosti.",
        "Šampionát je na dosah pro ty nejoddanější hráče.",
        "Moderní technologie nám umožňují simulovat realistická závodní prostředí.",
        "Kód je jako závodní dráha, musí být čistý a efektivní.",
        "Pocit z dokonalého kola se nevyrovná ničemu jinému ve sportu.",
        "Zůstaňte v klidu pod tlakem, abyste si udrželi výkon při psaní.",
        "Závodní dráha je náročné místo pro člověka i stroj.",
        "Zrychlení je klíčem k předjíždění soupeřů na rovince.",
        "Při psaní všemi deseti je důležité udržovat prsty v základní poloze.",
        "Kvalitní mechanická klávesnice může výrazně zlepšit váš pocit z psaní.",
        "Soustřeďte se na text před sebou a snažte se nedívat na své ruce.",
        "Každá chyba vás stojí drahocenné sekundy v tomto napínavém závodě.",
        "Adrenalin stoupá, když se přibližujete k poslední zatáčce před cílem.",
        "Plynulost je často důležitější než syrová rychlost úhozů za minutu.",
        "Vaše auto reaguje na každé správně napsané slovo okamžitým zrychlením.",
        "V tréninkovém režimu můžete pilovat svou techniku bez tlaku soupeřů.",
        "Závodní simulátory pomáhají profesionálním jezdcům učit se nové tratě.",
        "Precizní brzdění a včasná akcelerace jsou základy rychlého kola.",
        "Světlo světlometů prořezává tmu během nočního vytrvalostního závodu.",
        "Týmová strategie hraje klíčovou roli v moderních automobilových závodech.",
        "Aerodynamika vozu je navržena tak, aby poskytovala maximální přítlak.",
        "V boxové uličce se počítá každá desetina sekundy při výměně kol.",
        "Nezáleží na tom, jak pomalu jdete, dokud se nezastavíte.",
        "Úspěch je součtem malých snah opakovaných den co den.",
        "Vaše budoucnost je vytvářena tím, co děláte dnes, ne zítra.",
        "Nejlepší způsob, jak předpovědět budoucnost, je ji vytvořit.",
        "Cesta dlouhá tisíc mil začíná prvním krokem.",
        "Věřte, že to dokážete, a máte z poloviny vyhráno.",
        "Jediným omezením našeho zítřka jsou naše dnešní pochyby.",
        "Štěstí přeje připraveným, zejména na závodní trati.",
        "Snažte se být každý den o kousek lepší než včera.",
        "Vaše představivost je náhledem na nadcházející životní lákadla.",
        "Tvrdá práce poráží talent, když talent nepracuje tvrdě.",
        "Nikdy není pozdě být tím, čím jste mohli být.",
        "Změňte své myšlení a změníte svůj svět.",
        "Všechno, co jste kdy chtěli, je na druhé straně strachu.",
        "Překážky jsou ty věci, které vidíte, když spustíte oči ze svého cíle.",
        "Cílem není být lepší než ostatní, ale být lepší než své dřívější já.",
        "Soustředění je tajemstvím síly ve všech lidských činnostech.",
        "Trpělivost je hořká, ale její ovoce je sladké.",
        "Kvalita znamená dělat to dobře, i když se nikdo nedívá.",
        "Velké věci se nikdy nedělají z komfortních zón.",
        "Zůstaňte hladoví, zůstaňte blázniví, jak řekl Steve Jobs.",
        "Inovace rozlišuje mezi vůdcem a následovníkem.",
        "Design není jen to, jak to vypadá, ale jak to funguje.",
        "V jednoduchosti je krása a síla.",
        "Každý problém je příležitostí k růstu a učení.",
        "Učte se z včerejška, žijte pro dnešek a doufejte v zítřek.",
        "Důležité je nepřestat se ptát a stále objevovat nové věci.",
        "Logika vás dostane z bodu A do bodu B, představivost vás vezme kamkoli.",
        "Život je jako jízda na kole, abyste udrželi rovnováhu, musíte se hýbat.",
        "Pokusil ses. Selhal jsi. Nevadí. Zkus to znovu. Selži lépe.",
        "Znalost je moc, ale charakter je víc.",
        "Moudrost začíná úžasem nad světem kolem nás.",
        "Největší sláva netkví v tom, že nikdy nepadneme, ale v tom, že vždy vstaneme.",
        "Dělejte to, co můžete, s tím, co máte, tam, kde jste.",
        "Osud míchá karty, ale my s nimi hrajeme.",
        "Život není o čekání, až bouře přejde, ale o tom, jak se naučit tančit v dešti.",
        "Jediný způsob, jak dělat skvělou práci, je milovat to, co děláte.",
        "Váš čas je omezený, tak jím neplýtvejte na život někoho jiného.",
        "Mějte odvahu následovat své srdce a intuici.",
        "Buďte změnou, kterou chcete vidět ve světě.",
        "Slabí lidé se mstí, silní odpouštějí, inteligentní ignorují.",
        "Úsměv je nejkratší vzdálenost mezi dvěma lidmi.",
        "Laskavost je jazyk, který neslyšící slyší a slepí vidí.",
        "Vzdělání je nejmocnější zbraň, kterou můžete použít ke změně světa.",
        "Budoucnost patří těm, kdo věří v krásu svých snů.",
        "Neúspěch je prostě příležitost začít znovu, tentokrát inteligentněji.",
        "Když nemůžete létat, běžte. Když nemůžete běžet, jděte.",
        "Ať se děje cokoli, hlavně se hýbejte vpřed.",
        "Mír začíná úsměvem.",
        "Nic není nemožné, samotné slovo říká: jsem možné.",
        "Dělejte dnes to, za co si v budoucnu poděkujete.",
        "Vaše vášeň je vaší energií, pocit síly přichází z toho, co vás naplňuje.",
        "Pokud to dokážete snít, dokážete to i udělat.",
        "Hranice existují pouze v naší mysli.",
        "Vítěz je jen snílek, který se nikdy nevzdal.",
        "Hledejte příležitost v každé obtíži, ne obtíž v každé příležitosti.",
        "Buďte sami sebou, všichni ostatní už jsou obsazeni.",
        "Život je buď odvážné dobrodružství, nebo nic.",
        "Skutečné bohatství je to, kým jste, ne to, co máte.",
        "Méně mluvte, více dělejte a ukažte výsledky.",
        "Věřte v sebe a vše, čím jste.",
        "Uvnitř vás je něco, co je větší než jakákoli překážka.",
        "Úspěch není klíčem ke štěstí, štěstí je klíčem k úspěchu.",
        "Rozdíl mezi obyčejným a neobyčejným je to malé navíc.",
        "Soustřeďte se na cestu, ne na cíl.",
        "Radost se nenachází ve věcech, ale v nás samotných.",
        "Buďte hlasem, ne ozvěnou.",
        "Nejlepší odplatou je masivní úspěch.",
        "Každý den je nová šance změnit svůj život k lepšímu.",
        "Nebojte se vzdát dobrého, abyste získali to nejlepší.",
        "Motivace je to, co vás nastartuje, zvyk je to, co vás udrží v chodu.",
        "Nepočítejte dny, zařiďte, aby se dny počítaly.",
        "Kde je vůle, tam je i cesta.",
        "Nemožné je jen názor, ne fakt.",
        "Zůstaňte pozitivní, pracujte tvrdě a uskutečněte své sny.",
        "Všechno, co si dokážete představit, je skutečné.",
        "Nejsme definováni našimi neúspěchy, ale tím, jak na ně reagujeme.",
        "Síla nepochází z fyzické kapacity, ale z nezlomné vůle.",
        "Někdy vyhraješ, někdy se poučíš.",
        "Pokud procházíte peklem, nezastavujte se.",
        "Štěstí je volba, nikoli výsledek.",
        "Dělejte to, co je správné, ne to, co je snadné.",
        "Odvaha není absence strachu, ale vítězství nad ním.",
        "Buďte laskaví, kdykoli je to možné, a je to možné vždy.",
        "Žijte, jako byste měli zítra zemřít, učte se, jako byste měli žít navždy.",
        "Nejlepší věci v životě nejsou věci.",
        "Tajemství úspěchu je začít.",
        "Vaše práce zaplní velkou část vašeho života.",
        "Jediný způsob, jak být skutečně spokojený, je věřit v to, co děláte.",
        "Když milujete svou práci, nebudete muset pracovat ani jeden den.",
        "Úspěch je cesta, nikoli destinace.",
        "Nikdy se nevzdávejte snu jen kvůli času, který bude trvat ho dosáhnout.",
        "Čas stejně uplyne, tak ho využijte smysluplně.",
        "Všechny naše sny se mohou splnit, pokud budeme mít odvahu je následovat.",
        "Když se jedny dveře zavřou, jiné se otevřou.",
        "Hledejte krásu v maličkostech kolem sebe.",
        "Buďte trpěliví se sebou i s ostatními.",
        "Láska a práce jsou základy našeho lidství.",
        "Pravda osvobozuje, i když někdy bolí.",
        "Svoboda začíná tam, kde končí strach.",
        "Mějte velké sny a odvažte se selhat.",
        "Vaše hodnota nezávisí na názorech ostatních.",
        "Důvěřujte procesu a nevzdávejte se příliš brzy.",
        "Každé ráno máme novou příležitost začít znovu.",
        "Slunce svítí pro každého bez rozdílu.",
        "Voda, která teče, se nikdy nezkazí, tak se hýbejte.",
        "Buďte jako řeka, která si vždy najde cestu k oceánu.",
        "Hory volají a já musím jít objevovat svět.",
        "Příroda nepospíchá, a přesto je vše dokončeno.",
        "Klidná mysl přináší vnitřní sílu a sebevědomí.",
        "Dýchejte zhluboka a užívejte si přítomný okamžik.",
        "Život je dar, tak ho nezahoďte.",
        "Děkujte za to, co máte, a dostanete víc.",
        "Srdce, které děkuje, je vždy blízko zázrakům.",
        "Věřte v magii začátků.",
        "Všechno má svůj čas a místo pod sluncem."
    ],
    en: [
        "The quick brown fox jumps over the lazy dog.",
        "Racing is not just about speed, but also about focus and precision.",
        "To finish first, you must first finish.",
        "Keep your eyes on the road and your hands firmly on the keyboard.",
        "Fast typing is like shifting gears in a racing car.",
        "Victory belongs to those who make the fewest mistakes.",
        "The engine roars as the green light signals the start of the final lap.",
        "Practice makes perfect when it comes to touch typing skills.",
        "A steady rhythm is more important than a sudden burst of speed.",
        "The crowd cheers as the lead driver crosses the finish line.",
        "Formula One cars can reach amazing speeds on long straights.",
        "Focus on accuracy first, and speed will follow on its own.",
        "Every character typed brings you closer to the checkered flag.",
        "Don't look back; your opponent is breathing down your neck.",
        "Tires screech as the car takes a sharp corner at high speed.",
        "The championship is within reach for the most dedicated players.",
        "Modern technology allows us to simulate realistic racing environments.",
        "Code is like a race track; it must be clean and efficient.",
        "The feeling of a perfect lap is unlike anything else in sports.",
        "Stay calm under pressure to maintain your typing performance.",
        "The race track is a demanding place for both man and machine.",
        "Acceleration is the key to overtaking opponents on the straightaway.",
        "When touch typing, it's important to keep your fingers in the home position.",
        "A high-quality mechanical keyboard can greatly improve your typing feel.",
        "Concentrate on the text ahead and try not to look at your hands.",
        "Every mistake costs you precious seconds in this thrilling race.",
        "The adrenaline pumps as you approach the final turn before the finish.",
        "Fluidity is often more important than raw keystrokes per minute.",
        "Your car reacts to every correctly typed word with an immediate boost.",
        "In practice mode, you can hone your technique without the pressure of opponents.",
        "Racing simulators help professional drivers learn new tracks.",
        "Precise braking and timely acceleration are the basics of a fast lap.",
        "The beam of the headlights cuts through the dark during a night endurance race.",
        "Team strategy plays a crucial role in modern motor racing.",
        "The car's aerodynamics are designed to provide maximum downforce.",
        "In the pit lane, every tenth of a second counts during a tire change.",
        "It does not matter how slowly you go as long as you do not stop.",
        "Success is the sum of small efforts repeated day in and day out.",
        "Your future is created by what you do today, not tomorrow.",
        "The best way to predict the future is to create it.",
        "A journey of a thousand miles begins with a single step.",
        "Believe you can and you are halfway there.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Luck favors the prepared mind, especially on the race track.",
        "Strive to be a little better every day than you were yesterday.",
        "Your imagination is your preview of life's coming attractions.",
        "Hard work beats talent when talent doesn't work hard.",
        "It is never too late to be what you might have been.",
        "Change your thoughts and you change your world.",
        "Everything you've ever wanted is on the other side of fear.",
        "Obstacles are those frightful things you see when you take your eyes off your goal.",
        "The goal is not to be better than the other man, but your previous self.",
        "Concentration is the secret of strength in all human affairs.",
        "Patience is bitter, but its fruit is sweet.",
        "Quality means doing it right when no one is looking.",
        "Great things never come from comfort zones.",
        "Stay hungry, stay foolish, as Steve Jobs once said.",
        "Innovation distinguishes between a leader and a follower.",
        "Design is not just what it looks like and feels like. Design is how it works.",
        "Simplicity is the ultimate sophistication.",
        "Every problem is an opportunity for growth and learning.",
        "Learn from yesterday, live for today, hope for tomorrow.",
        "The important thing is not to stop questioning and exploring.",
        "Logic will get you from A to B. Imagination will take you everywhere.",
        "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        "Ever tried. Ever failed. No matter. Try again. Fail better.",
        "Knowledge is power, but character is more.",
        "Wisdom begins in wonder of the world around us.",
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "Do what you can, with what you have, where you are.",
        "Fate shuffles the cards, but we play them.",
        "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.",
        "The only way to do great work is to love what you do.",
        "Your time is limited, so don't waste it living someone else's life.",
        "Have the courage to follow your heart and intuition.",
        "Be the change that you wish to see in the world.",
        "Weak people revenge. Strong people forgive. Intelligent people ignore.",
        "A smile is the shortest distance between two people.",
        "Kindness is the language which the deaf can hear and the blind can see.",
        "Education is the most powerful weapon which you can use to change the world.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Failure is simply the opportunity to begin again, this time more intelligently.",
        "If you can't fly then run, if you can't run then walk, if you can't walk then crawl.",
        "No matter what happens, keep moving forward.",
        "Peace begins with a smile.",
        "Nothing is impossible, the word itself says 'I'm possible'!",
        "Do something today that your future self will thank you for.",
        "Your passion is your energy. Feel the power that comes from focusing on what excites you.",
        "If you can dream it, you can do it.",
        "Limits exist only in the mind.",
        "A winner is a dreamer who never gives up.",
        "Look for opportunity in every difficulty, not difficulty in every opportunity.",
        "Be yourself; everyone else is already taken.",
        "Life is either a daring adventure or nothing at all.",
        "True wealth is who you are, not what you have.",
        "Talk less, do more, and show results.",
        "Believe in yourself and all that you are.",
        "There is something inside you that is greater than any obstacle.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The difference between ordinary and extraordinary is that little extra.",
        "Focus on the journey, not the destination.",
        "Joy is not in things; it is in us.",
        "Be a voice, not an echo.",
        "The best revenge is massive success.",
        "Each day is a new chance to change your life for the better.",
        "Don't be afraid to give up the good to go for the great.",
        "Motivation is what gets you started. Habit is what keeps you going.",
        "Don't count the days, make the days count.",
        "Where there is a will, there is a way.",
        "Impossible is just an opinion, not a fact.",
        "Stay positive, work hard, and make it happen.",
        "Everything you can imagine is real.",
        "We are not defined by our failures but by how we respond to them.",
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Sometimes you win, sometimes you learn.",
        "If you are going through hell, keep going.",
        "Happiness is a choice, not a result.",
        "Do what is right, not what is easy.",
        "Courage is not the absence of fear, but the triumph over it.",
        "Be kind whenever possible. It is always possible.",
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "The best things in life aren't things.",
        "The secret of getting ahead is getting started.",
        "Your work is going to fill a large part of your life.",
        "The only way to be truly satisfied is to do what you believe is great work.",
        "When you love your work, you will never have to work a day in your life.",
        "Success is a journey, not a destination.",
        "Never give up on a dream just because of the time it will take to accomplish it.",
        "The time will pass anyway, so use it meaningfully.",
        "All our dreams can come true, if we have the courage to pursue them.",
        "When one door closes, another opens.",
        "Find beauty in the little things around you.",
        "Be patient with yourself and others.",
        "Love and work are the cornerstones of our humaneness.",
        "The truth sets you free, even if it hurts sometimes.",
        "Freedom begins where fear ends.",
        "Dream big and dare to fail.",
        "Your value does not depend on the opinions of others.",
        "Trust the process and do not give up too soon.",
        "Every morning we have a new opportunity to start over.",
        "The sun shines for everyone without distinction.",
        "Water that flows never goes stale, so keep moving.",
        "Be like a river that always finds its way to the ocean.",
        "The mountains are calling and I must go explore the world.",
        "Nature does not hurry, yet everything is accomplished.",
        "A calm mind brings inner strength and self-confidence.",
        "Breathe deeply and enjoy the present moment.",
        "Life is a gift, so don't throw it away.",
        "Give thanks for what you have and you will get more.",
        "A heart that gives thanks is always close to miracles.",
        "Believe in the magic of beginnings.",
        "Everything has its time and place under the sun."
    ]
};
